#!/bin/bash
if [ $# -ne 1 ]; then
    echo "Requires 1 argument. Time in minutes to stay on for."
    exit 1
fi

dbus-send --system --type=method_call --print-reply --dest=org.cacophony.Attiny /org/cacophony/Attiny org.cacophony.Attiny.StayOnFor int64:$1
